### ISSUE TITLE
After installation from Ubuntu PPA neoman crashes on startup

### ISSUE THREAD

**Issue by Rovanion** [Yubico/yubikey-neo-manager#40]
After installing neoman from the Ubuntu PPA I get the following failure to start:

``` bash
$ neoman 
Traceback (most recent call last):
  File "/usr/local/bin/neoman", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PySide
```

These are the pyside related packages that are installed on my system:

``` bash
dpkg -l | grep pyside
ii  libpyside1.2:i386                                                1.2.1-4build1                                 i386         Python bindings for Qt 4 (base files)
ii  python-pyside                                                    1.2.1-4build1                                 all          Python bindings for Qt4 (big metapackage)
ii  python-pyside.phonon                                             1.2.1-4build1                                 i386         Qt 4 Phonon module - Python bindings
ii  python-pyside.qtcore                                             1.2.1-4build1                                 i386         Qt 4 core module - Python bindings
ii  python-pyside.qtdeclarative                                      1.2.1-4build1                                 i386         Qt 4 Declarative module - Python bindings
ii  python-pyside.qtgui                                              1.2.1-4build1                                 i386         Qt 4 GUI module - Python bindings
ii  python-pyside.qthelp                                             1.2.1-4build1                                 i386         Qt 4 help module - Python bindings
ii  python-pyside.qtnetwork                                          1.2.1-4build1                                 i386         Qt 4 network module - Python bindings
ii  python-pyside.qtopengl                                           1.2.1-4build1                                 i386         Qt 4 OpenGL module - Python bindings
ii  python-pyside.qtscript                                           1.2.1-4build1                                 i386         Qt 4 script module - Python bindings
ii  python-pyside.qtsql                                              1.2.1-4build1                                 i386         Qt 4 SQL module - Python bindings
ii  python-pyside.qtsvg                                              1.2.1-4build1                                 i386         Qt 4 SVG module - Python bindings
ii  python-pyside.qttest                                             1.2.1-4build1                                 i386         Qt 4 test module - Python bindings
ii  python-pyside.qtuitools                                          1.2.1-4build1                                 i386         Qt 4 UI tools module - Python bindings
ii  python-pyside.qtwebkit                                           1.2.1-4build1                                 i386         Qt 4 WebKit module - Python bindings
ii  python-pyside.qtxml                                              1.2.1-4build1                                 i386         Qt 4 XML module - Python bindings
```

**Comment by lfaraone** [comment]
Looks like you're on Ubuntu 15.04 ("Vivid Vervet"); is that correct?

**Comment by Rovanion** [comment]
Yes

**Comment by dainnilsson** [comment]
If you installed from the PPA the neoman binary shouldn't be in /usr/local/bin, it should be in /usr/bin. I suspect you have a (partial?) manual installation in /usr/local/bin, perhaps from pip, which is unable to see your PySide installation. Try removing the installation in /usr/local/bin.

**Comment by Rovanion** [comment]
Yes that might have been it. I had started an install from source previously before I found the PPA, which I cancelled once I found it. Turns out that removing an installation from setup.py is quite dirty though: 

```
python setup.py install --record files.txt
cat files.txt | xargs rm
```
