### ISSUE TITLE
How to use on debian - ubuntu links broken

### ISSUE THREAD

**Issue by schallee** [Yubico/yubikey-neo-manager#48]
Admittedly I am not a python person but I am failing to discover how to even run this on debian jessie amd64. The links provided for a custom ubuntu PPA are broken so that doesn't help either.

After installing as many python packages as seemed needed (python-pyside, python-pip, python-setuptools and python-nose) and installing pyinstaller through pip I attempted to run the pyinstaller command for osx resulting in the following:

pyinstaller resources/neoman.spec 
12 INFO: PyInstaller: 3.0
13 INFO: Python: 2.7.9
16 INFO: Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
24 INFO: UPX is available.
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 99, in run
    run_build(opts, spec_file, pyi_config)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 47, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 680, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 161, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script 'resources/scripts/neoman' not found

I have attempted this with both the most recent tarball and from git with similar results. Further directions and link corrections would be appreciated.

**Comment by dainnilsson** [comment]
The PPA links were broken on developers.yubico.com (now fixed), but have always been available in the README of this repository. For a Debian package, look here: https://packages.debian.org/sid/main/yubikey-neo-manager

**Comment by schallee** [comment]
As much as I do with debian I can't believe I missed that. Thanks!

**Comment by dorvan** [comment]
also I since my first mail in october. abut this.
